### ISSUE TITLE
Lift curries implicit binary function

### ISSUE THREAD

**Issue by 5310** [citycide/param.macro#15]
I encountered an instance where I think `lift()` isn't working as expected. Instead of lifting a binary function, it curries it!

```js
import { _, it, lift } from 'param.macro'

const swap = (a, b) => _(b, a)

const map1 = _.map(_)  
const map2 = swap(lift(_.map(_))) // lift curries ✘

console.log(map1([0, 1, 2], lift(_ * 10))) // [0, 10, 20] ✔
console.log(map2(lift(_ * 10), [0, 1, 2])) // [function]  ✘
```

[[Playground link](https://citycide.github.io/param.macro/#code/JYWwDg9gTgLgBAbzgfQDR2DdAbYAzeAXzjyghDgHIwBDKGkAOhBoGMzKAoT1iAOwDO8AQHcaYOAF44AChroARgEopAPhQyF6Gku69B8FmACMUlM3EzkKuD35C4RgExnRl3ASsWwVpX7gA9AFwHvCsAK5QUMAApgJwgBjkevYQ2DGM2BAA5jJGxjIA2gAM6MboTgC6OPgwVnAAVHDGRX4qQXDFpSVwTkUVcIAo5HaCqemZOc4yoXWNzUronU3lFf7tBXjhfKwwwPz9iUA)]

I am expecting `map2` to look like this:

```js
const map2 = swap((_arg2, _arg3) => {
  return _arg2.map(_arg3)
})
```

But it returns as this:

```js
const map2 = swap(_arg4 => {
  return _arg5 => {
    return _arg4.map(_arg5)
  }
})
```

Is this intended?

**Comment by citycide** [comment]
Hey @5310, thanks for the issue. This one can be a bit confusing so I'm going to step through it, starting with the original declaration:

```js
const map2 = swap(lift(_.map(_)))
```

The first thing that happens is the `_` placeholder transformation, and the first one we come across is the object of the map call:

```js
const map2 = swap(_arg4 => {
  return lift(_arg4.map(_))
})
```

Because it's wrapped in `lift`, the transformation takes place inside the `swap` argument list. Without `lift` the wrapper would be _above_ the `swap` call (`map2` would be a function returning the result of `swap`).

Then the remaining `_` placeholder is replaced &mdash; remember these traverse upward out of their nearest argument list, which in this case is the `.map(...)` call and leaves the resulting function within the `lift` wrapper:

```js
const map2 = swap(_arg4 => {
  return lift(_arg5 => {
    return _arg4.map(_arg5)
  })
})
```

Then the `lift` macro takes effect, removing that wrapper function:

```js
const map2 = swap(_arg4 => {
  return _arg5 => {
    return _arg4.map(_arg5)
  }
})
```

Given those transformation steps I think each piece is working according to the rules. I believe what you were trying to accomplish was this:

```js
const map2 = swap(it.map(_))
```

See this working [on the playground](https://citycide.github.io/param.macro/#code/JYWwDg9gTgLgBAbzgfQDR2DdAbYAzeAXzjyghDgHIwBDKGkAOhBoGMzKAoT1iAOwDO8AQHcaYOAF44AChroARgEopAPhQyF6Gku69B8FmACMUlM3EzkKuD35C4RgExnRlzBbBWluu4IjYAKaM2BAA5jJGxjIA2gAM6MboTgC6OPgwVnAAVHDGcT4qAPRFcPGJCXBOcSlwgCjkfgIBwaERzjK4BFm5+Uro5XnJKT5wJWWV+ck19UA).

It all basically comes down to the fact that `_.map(_)` isn't really a _binary function_ like `lift` is meant to modify &mdash; it's an _unary method_. `lift` is only a _ceiling_ (I call it a [C-C-CONTEXT BREAKER](https://knowyourmeme.com/memes/combo-breaker)) and prevents `_` from traversing further upward, so it doesn't do anything to bring more deeply nested placeholders _upward_. The normal rules of the `_` placeholder actually still apply.

Does this make sense or solve your problem? Is it a documentation problem?

**Comment by citycide** [comment]
That's a start at least, though it could be more brief. What about this:

* change `const hasOwn = _.hasOwnProperty(_)` to `const hasOwn = it.hasOwnProperty()`
* maybe specify that the top level like the RHS of assignments is the only place where `_` and `it` can act similarly &mdash; since there's no further upward to go they can both stop at the same place.
* be more clear with the last part of the `lift` section:

  > It may be helpful to note that `_` is still following its own rules here: it traversed upward out of its parent function call! It just so happens that call is removed afterward leaving your new function exactly where you want it.

If you're into it I'd appreciate a PR we can go over.

**Comment by 5310** [comment]
How about we add the following to the scoping sub-section under the differences between `it` and `_`:

> Likewise, only at the top level as the right-hand side of an assignment does `it` and `_` behave similarly when used to produce implicit n-ary functions — since there's no further upward to go they can both stop at the same place.
>
> The following two map implementations do the same thing.
>
> ```js
> import { _, it } from 'param.macro'
> 
> const map1 = _.map(_)
> const map2 = it.map(_)
> ```
>
> However, if nested deeper inside a function call,the object placeholder `_` would traverse upward and create a separate function before being passed the `_` inside the method call itself. This creates a unary method call instead of the implicit binary function we might think in this case, `lift` or not.
>
> The `it` implementation still creates the implicit binary function we want, even if nested deeper. And following their own rules any `_` inside the method call will traverse up to the method call and stop to create a function there.
