### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by woudsma** [citycide/param.macro#8]
Quickly tried out `param.macro` in a `create-react-app` application we're working on, but i can't get the plugin to work so far. I like the idea a lot though!

.babelrc
```
{
  "presets": [],
  "plugins": ["babel-plugin-macros"]
}
```

Trying `it` with a Promise, gives an `Uncaught (in promise) TypeError: Cannot read property 'data' of undefined` error.
```js
import { it } from 'param.macro'
// ...

async initialize() {
  const vertexShader = await axios.get(vertexSource).then(it.data)

  // this works
  // const vertexShader = await axios.get(vertexSource).then(e => e.data)
}
```
Maybe i'm doing something wrong here. Also tried out mapping over a simple array 
`[{a:11},{a:22}].map(it.a)`, which gives the same TypeError.

-Edit- `console.log(it)` returns `undefined` as well i see now, so maybe it's caused by the `create-react-app` way of compiling code.

**Comment by citycide** [comment]
Hey @woudsma thanks for reporting, I'll check it out. In the meantime if you can provide a minimal repro case before I respond that'd help me debug.

**Comment by citycide** [comment]
I wasn't able to reproduce using `create-react-app@2.0.0-next.9754a231` + `react-scripts@2.0.0-next.9754a231`. If you're able to reduce your code and still have the issue let me know. It sounds like you might be ejected though, since you're controlling your own `.babelrc`? More info about your environment like versions of Node, Babel, `create-react-app`, `param.macro` etc. would be helpful.

My steps were:

1. `yarn global add create-react-app@2.0.0-next.9754a231`
2. `create-react-app param.macro-bug`
3. `cd param.macro-bug && yarn upgarde react-scripts@2.0.0-next.9754a231`
4. `yarn add param.macro`
5. Update `./src/App.js` to this:

    ```js
    import React, { Component } from 'react';
    import { it } from 'param.macro';
    import logo from './logo.svg';
    import './App.css';

    function foo () {
      return Promise.resolve({ data: 'hello' });
    }

    class App extends Component {
      render() {

        foo().then(it.data).then(console.log);
        // -> 'hello'

        return (
          <div className="App">
            <header className="App-header">
              <img src={logo} className="App-logo" alt="logo" />
              <h1 className="App-title">Welcome to React</h1>
            </header>
            <p className="App-intro">
              To get started, edit <code>src/App.js</code> and save to reload.
            </p>
          </div>
        );
      }
    }

    export default App;
    ```

6. `yarn start`

**Comment by woudsma** [comment]
I see, we didn't eject, but were still on `react-scripts@1.1.0`. Updating to `react-scripts@2.0.0-next` solves the problem. Also no need for a custom `.babelrc` in this case, because `babel-macros` is included in `react-scripts@2.x`. Thanks for pointing that out!

**Comment by citycide** [comment]
No problem! Let me know when you've had a chance to use `param.macro` and if you'd want to share it - I'd like to start a section of the readme or another file for a showcase.
