### ISSUE TITLE
How to create simple implicit functions

### ISSUE THREAD

**Issue by danielo515** [citycide/param.macro#9]
Hello,

Thanks for your macros, they're great. 
I was wondering if it is possible, and if it is how, can I make implicit binary functions. Something in between `_` and `it`

```js
[1,2,3,4].reduce( _ + _)
```

The expected output would be

```js
[1,2,3,4].reduce( (arg1, arg2) => arg1 + arg2 )
```

But instead I get:

```js
;(_arg2, _arg3) => {
  return [1, 2, 3, 4].reduce(_arg2 + _arg3)
}
```

Regards

**Comment by citycide** [comment]
> Thanks for your macros, they're great.

Thanks! :smile:

> I was wondering if it is possible, and if it is how, can I make implicit binary functions. Something in between `_` and `it`

I mostly believe that if your function isn't as simple as `_` and `it` can currently handle, you should probably extract it. It would also lead to a more complex implementation &mdash; how do we signal the intent? I'm really not sure how it could be supported with the current 'syntax'.

I'm all for being convinced and you're totally welcome to make some proposals but right now I'd call this out of scope.

**Comment by danielo515** [comment]
Hello @citycide 
I think that a binary function is as simple as an unary one. In fact, it is simpler than the current behavior of `_`, which could be a bit unexpected some times. I mean, it wraps the entire block on a function, which sometimes is hard to predict where the block will start.

I am not suggesting to change the behavior of the current operators, but to add a new one with this behavior. I'm not sure about the symbol because I'm not sure of the capabilities of babel-macros. I think macro names should be valid variable names, so things like `_?` or `:?` can not be used. What about `it$` or `_$` ?

I think this is similar and simple enough to be included on this same package. In fact what I'm proposing is the same thing the Scala `_` macro does (which you stated on your readme that is simpler 😄 )

**Comment by citycide** [comment]
> the current behavior of `_`, which could be a bit unexpected some times. I mean, it wraps the entire block on a function, which sometimes is hard to predict where the block will start.

This should be pretty clear from the [scoping section](https://github.com/citycide/param.macro#scoping) of the readme:

_`_` will always traverse upward out of the nearest function call, while `it` will be transformed in place._

Maybe instead of adding a yet another token with slightly different rules, maybe we could add a sort of "dummy" macro like this:

```js
// calling it lift because it's the first thing that came to mind
import { _, lift } from 'param.macro'

;[1,2,3,4].reduce(lift(_ + _))

// equivalent to:
;[1,2,3,4].reduce((_arg, _arg2) => _arg + _arg2)
```

... where the `lift` call would be elided entirely. This wouldn't require a change in any existing behavior.

You could even just do this to approximate it with the current release (paste it into the [playground](https://citycide.github.io/param.macro/)), but this has non-zero overhead due to the additional function call:

```js
import { _ } from 'param.macro'

const lift = _
;[1,2,3,4].reduce(lift(_ + _))
```

**Comment by danielo515** [comment]
I like the idea. However lift seems too long :smile:
This reminds me to the implicit function plugin, which uses the ~ as operator for things like `~x` resulting in `() =>x`
In fact, maybe they play good together. I'll check!

**Comment by citycide** [comment]
@danielo515 I'd rather it be a descriptive name for something like this - I personally dislike the symbol soup that you can end up in with languages like Haskell and want to hold a middle ground. You could always alias the import yourself though:

```js
import { _, lift as $ } from 'param.macro'

;[1,2,3,4].reduce($(_ + _))
```

> In fact, maybe they play good together. I'll check!

Please do, and report back 👍

**Comment by danielo515** [comment]
Yes, you're right. That is something I really like about lisp. I totally forget that I can rename the macro to whatever I want.
I'll check anyway

**Comment by citycide** [comment]
@danielo515 I tried using [`babel-plugin-implicit-function`](https://github.com/haskellcamargo/babel-plugin-implicit-function) with `param.macro`, it doesn't work as you were hoping:

```js
// in
import { _ } from 'param.macro'

;[1, 2, 3, 4].reduce(~(_ + _))
```

```js
// out
(_arg, _arg2) => {
  return [1, 2, 3, 4].reduce(() => _arg + _arg2);
};
```

This is due to the order in which the plugins run, since `param.macro` has an earlier visitor than `implicit-function`. If `implicit-function` were a macro it'd be easy to make it run first by just importing it first, but then you wouldn't be able to use the `~` character.

I'll think this over and consider adding something like `lift` &mdash; anybody interested should add a comment, I'd appreciate input from others. And if it'll get added we'll need to settle on a name for it.

**Comment by danielo515** [comment]
Hey @citycide 
Thank you very much for trying !
I was fearing that, however I though you (the user) would be able to control the plugin precedence by just chaniging the order on the plugins array, how fool I was !

In any case, I prefer your explicit readable solution that does not highjack any operator 😄 I will probably rename it as `L` or something like that. I'll be happy with just lift.

Regards

**Comment by citycide** [comment]
@danielo515 I put up PR #11 to take care of this, hope you can check it out and see if it's 👍

**Comment by danielo515** [comment]
Hello @citycide 
I just tried the new feature and I can confirm that it works as expected. Terrific work, many thanks !!!

**Comment by citycide** [comment]
@danielo515 it's now in the stable release [v2.1.0](https://github.com/citycide/param.macro/releases/tag/v2.1.0). The online playground supports it and has permalink support now, so you can click this link to check it out:

https://citycide.github.io/param.macro/#code/JYWwDg9gTgLgBAbzgfQDRwDbAGbwL5zZQQhwDkYAhlJSAHQiUDGxZAUG0xAHYDO81GgE84AXjgBtAIzoATOgDM6ACzoArAF1OPfnF4BXUuMGUhdKAFMAJvqYWAFFlz3kcANQoAlJ+18IGCzoMCABzewMQHwB6KLgAWgA+OCk1IA
